#!/usr/bin/env node
// Keeps README.md in sync with what is actually on disk.
//
//  1. Regenerates the SELECTED WORK grid between the showcase markers, so adding
//     a project is a one-line edit to data/projects.json — and a card whose demo
//     clip has been recorded shows the clip above it automatically.
//  2. Stamps every asset URL with a hash of that file's contents. GitHub proxies
//     images through camo and caches them hard; without a changing query string a
//     refreshed card can sit stale in the page for hours. The hash only moves when
//     the asset really changed, so the README isn't churned for nothing.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';

const CFG = JSON.parse(readFileSync('data/projects.json', 'utf8'));
const OWNER = process.env.GH_LOGIN || CFG.owner;
const RAW = `https://raw.githubusercontent.com/${OWNER}/${OWNER}/main`;
const START = '<!-- showcase:start -->', END = '<!-- showcase:end -->';
const CHIPS_START = '<!-- chips:start -->', CHIPS_END = '<!-- chips:end -->';

const ver = file => existsSync(file)
  ? createHash('sha1').update(readFileSync(file)).digest('hex').slice(0, 8)
  : '0';

const linkOf = p => p.url || `https://github.com/${OWNER}/${p.repo}`;
const alt = s => String(s).replace(/"/g, '&quot;');

function cell(p, i) {
  const href = linkOf(p);
  const card = `assets/proj-${i + 1}.svg`;
  const clip = `assets/demos/${p.repo}.gif`;
  const parts = [];
  if (existsSync(clip)) {
    parts.push(`<a href="${href}"><img src="${RAW}/${clip}?v=${ver(clip)}" width="100%" alt="${alt(p.name)} — recorded demo" /></a>`);
  }
  parts.push(`<a href="${href}"><img src="${RAW}/${card}?v=${ver(card)}" width="100%" alt="${alt(`${p.name} — ${p.blurb}`)}" /></a>`);
  return `<td width="50%" valign="top">${parts.join('')}</td>`;
}

const rows = [];
for (let i = 0; i < CFG.projects.length; i += 2) {
  const pair = CFG.projects.slice(i, i + 2).map((p, k) => cell(p, i + k));
  if (pair.length === 1) pair.push('<td width="50%"></td>');
  rows.push(`<tr>\n${pair.join('\n')}\n</tr>`);
}

const notes = CFG.projects.filter(p => p.note).map(p =>
  `<details>\n<summary><sub><b>${p.name}</b> — director's commentary</sub></summary>\n\n<sub>${p.note}</sub>\n\n</details>`);

const clips = CFG.projects.filter(p => existsSync(`assets/demos/${p.repo}.gif`)).length;
const block = [
  START,
  `<!-- generated by scripts/build-readme.mjs — edit data/projects.json, not this block -->`,
  `<table>`,
  ...rows,
  `</table>`,
  ...(notes.length ? ['', ...notes] : []),
  END,
].join('\n');

// the contact row, so adding a link is a one-line edit to data/projects.json
const chipBlock = [
  CHIPS_START,
  ...CFG.contact.map(c => {
    const f = `assets/chip-${c.label.toLowerCase()}.svg`;
    return `<a href="${c.url}"><img src="${RAW}/${f}?v=${ver(f)}" height="34" alt="${alt(c.label.toLowerCase())}" /></a>`;
  }),
  CHIPS_END,
].join('\n');

let md = readFileSync('README.md', 'utf8');
for (const [a, b] of [[START, END], [CHIPS_START, CHIPS_END]]) {
  if (!md.includes(a) || !md.includes(b)) {
    console.error(`README.md is missing the ${a} / ${b} markers — nothing to do.`);
    process.exit(1);
  }
}
md = md.slice(0, md.indexOf(START)) + block + md.slice(md.indexOf(END) + END.length);
md = md.slice(0, md.indexOf(CHIPS_START)) + chipBlock + md.slice(md.indexOf(CHIPS_END) + CHIPS_END.length);

// stamp every asset reference with its content hash
const rx = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
md = md.replace(
  new RegExp(`(${rx(RAW)}/assets/[\\w./-]+?)(\\?v=[\\w.]+)?(?=["')\\s])`, 'g'),
  (_, url) => `${url}?v=${ver(url.slice(RAW.length + 1))}`);

writeFileSync('README.md', md);
console.log(`README synced — ${CFG.projects.length} projects, ${clips} demo clip${clips === 1 ? '' : 's'}, ${notes.length} commentary note${notes.length === 1 ? '' : 's'}`);
